name: flutter_template_viewer
description: A small package to facilitate view flutter widget templates
version: 0.0.1
author: Adriano Moreira
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   assets:
     - skins/